app:
  title: Backstage Example App
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7000
  bindPort: 7000
  bindHost: localhost
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true

organization:
  name: Spotify
