#!/usr/bin/env docker-compose -f

version: "3.4"

services:
  proxy:
    container_name: boss-proxy
    build:
      context: backend/proxy
    restart: unless-stopped
    ports:
      - "8080:80"

  identity:
    container_name: boss-identity
    build:
      context: backend
      target: default
      args:
        service: identity
    restart: unless-stopped
    volumes:
       - ./backend/identity/identity-data.json:/app/identity-data.json

  builds:
    container_name: boss-builds
    build:
      context: backend
      target: default
      args:
        service: builds
    restart: unless-stopped
    env_file: secrets.env

  scaffolder:
    container_name: boss-scaffolder
    build:
      context: backend
      target: scaffolder
      args:
        service: scaffolder
    restart: unless-stopped
