#!/usr/bin/env docker-compose -f

version: "3.4"

services:
  proxy:
    container_name: boss-proxy
    build:
      context: backend/proxy
    restart: unless-stopped
    ports:
      - "8080:80"

  # identity:
  #   container_name: boss-identity
  #   build:
  #     context: backend/identity
  #   restart: unless-stopped

  # inventory:
  #   container_name: boss-inventory
  #   build:
  #     context: backend/inventory
  #   restart: unless-stopped

  scaffolder:
    container_name: boss-scaffolder
    build:
      context: backend/scaffolder
    restart: unless-stopped


