#!/usr/bin/env docker-compose -f

version: "3.4"

services:
  proxy:
    container_name: boss-proxy
    build:
      context: proxy
    restart: unless-stopped
    ports:
      - "8080:80"

  identity:
    container_name: boss-identity
    build:
      context: .
      args:
        service: identity
    restart: unless-stopped
    volumes:
       - ./identity/identity-data.json:/app/identity-data.json

  inventory:
    container_name: boss-inventory
    build:
      context: .
      args:
        service: inventory
    restart: unless-stopped
    volumes:
      - ./inventory/inventory.db:/app/inventory.db

  builds:
    container_name: boss-builds
    build:
      context: .
      args:
        service: builds
    restart: unless-stopped
    env_file: ../secrets.env
    depends_on:
      - inventory
    links:
      - inventory

  scaffolder:
    depends_on:
      - inventory
    links:
      - inventory
    build:
      context: .
      args:
        service: scaffolder
        base_image: scaffolder
    restart: unless-stopped
    volumes:
      - ./scaffolder/templates:/app/templates:ro

    env_file: ../secrets.env
