apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shuffle-api
  description: Shuffle API
  annotations:
    backstage.io/github-actions-id: 'spotify/backstage'
spec:
  type: service
  lifecycle: production
  owner: guest
