apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: boxoffice
  description: The boxoffice sub-department
spec:
  type: sub-department
  parent: infrastructure
  ancestors: [infrastructure, acme-corp]
  children: [team-c, team-d]
  descendants: [team-c, team-d]
