apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The infra department
spec:
  type: department
  parent: acme-corp
  ancestors: [acme-corp]
  children: [backstage, boxoffice]
  descendants: [backstage, boxoffice, team-a, team-b, team-c, team-d]
