apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: The backstage sub-department
spec:
  type: sub-department
  parent: infrastructure
  ancestors: [infrastructure, acme-corp]
  children: [team-a, team-b]
  descendants: [team-a, team-b]
