{{- $frontendUrl := urlParse .Values.appConfig.app.baseUrl}}
{{- $backendUrl := urlParse .Values.appConfig.backend.baseUrl}}
{{- $lighthouseUrl := urlParse .Values.appConfig.lighthouse.baseUrl}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "backstage.fullname" . }}-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ $frontendUrl.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "frontend.serviceName" . }}
              servicePort: 80
          - path: /techdocs
            backend:
              serviceName: {{ include "backend.serviceName" . }}
              servicePort: 80
          - path: /metadata
            backend:
              serviceName: {{ include "backend.serviceName" . }}
              servicePort: 80
    - host: {{ $backendUrl.host }}
      http:
        paths:
          - path: {{ $backendUrl.path | default "/" }}
            backend:
              serviceName: {{ include "backend.serviceName" . }}
              servicePort: 80
    - host: {{ $lighthouseUrl.host }}
      http:
        paths:
          - path: {{ $lighthouseUrl.path | default "/" }}
            backend:
              serviceName: {{ include "lighthouse.serviceName" . }}
              servicePort: 80

