apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "backstage.fullname" . }}-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: {{ include "backend.serviceName" . }}
          servicePort: 80
      - path: /
        backend:
          serviceName: {{ include "frontend.serviceName" . }}
          servicePort: 80

