name: Frontend CI

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    env:
      CI: true
      BACKSTAGE_CACHE_DIR: <repoRoot>/.backstage-build-cache
      BACKSTAGE_CACHE_MAX_ENTRIES: 2

    steps:
      - uses: actions/checkout@v2
      - name: fetch branch master
        run: git fetch origin master
      - name: find location of global yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: cache global yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: cache build cache
        uses: actions/cache@v1
        with:
          path: .backstage-build-cache
          key: build-cache-${{ github.sha }}
          restore-keys: |
            build-cache-
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - name: yarn bundle, if app was changed
        run: git diff --quiet origin/master HEAD -- packages/app packages/core || yarn bundle
      - name: verify storybook
        run: yarn workspace storybook build-storybook
