name: TechDocs

on:
  pull_request:
    paths:
      - '.github/workflows/techdocs.yml'
      - 'packages/techdocs-container/**'
      - 'packages/techdocs-cli/**'
      - 'plugins/techdocs/**'
      - 'plugins/techdocs-backend/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    env:
      TECHDOCS_CORE_PATH: ./packages/techdocs-container/techdocs-core

    name: Python ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      # Build Docker Image
      - name: Build Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          path: packages/techdocs-container
          push: false
