name: TechDocs

on:
  pull_request:
    paths:
      - '.github/workflows/techdocs.yml'
      - 'packages/techdocs-cli/**'
      - 'plugins/techdocs/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    name: Python ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      # Validate Docker Container
      - name: prepare docker build
        working-directory: ${{ runner.temp }}
        run: ls
      - name: verify docker build
        uses: docker/build-push-action@v1
        with:
          repository: spotify/techdocs
          push: false

      # Lint Python code for techdocs-core package
      - name: lint techdocs-core package
        working-directory: ${{ runner.temp }}/plugins/techdocs/mkdocs/container/techdocs-core
        run: |
          pip install -r requirements.txt
          python -m black --check src/
