name: TechDocs

on:
  pull_request:
    paths:
      - '.github/workflows/techdocs.yml'
      - 'packages/techdocs-container/**'
      - 'packages/techdocs-cli/**'
      - 'plugins/techdocs/**'
      - 'plugins/techdocs-backend/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    env:
      TECHDOCS_CORE_PATH: ./packages/techdocs-container/techdocs-core

    name: Python ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      # Build Docker Image
      - name: Build Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          path: packages/techdocs-container
          push: false

      # Lint Python code for techdocs-core package
      - name: prepare python environment
        run: |
          python3 -m pip install --index-url https://pypi.org/simple/ setuptools
          python3 -m pip install --upgrade pip
          python3 -m pip install --index-url https://pypi.org/simple/ -r $TECHDOCS_CORE_PATH/requirements.txt

      - name: lint techdocs-core package
        run: |
          python3 -m black --check $TECHDOCS_CORE_PATH/src
      
      # Publish techdocs-core to PyPI
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Build Python distribution
        run: |
          pip install wheel
          rm -rf $TECHDOCS_CORE_PATH/dist
          python $TECHDOCS_CORE_PATH/setup.py bdist_wheel sdist --formats gztar
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_api_key }}
          packages_dir: $TECHDOCS_CORE_PATH/dist