name: TechDocs

on:
  pull_request:
    paths:
      - '.github/workflows/techdocs.yml'
      - 'packages/techdocs-cli/**'
      - 'plugins/techdocs/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    name: Python ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      # Lint Python code for techdocs-core package
      - name: lint techdocs-core package
        working-directory: ./plugins/techdocs/mkdocs/container/techdocs-core
        run: |
          python3 -m pip3 install --upgrade pip
          python3 -m pip3 install --index-url https://pypi.org/simple/ -r requirements.txt
          python3 -m black --check src/
